Add neutron_tempest_plugin to tempest dependencies
This is required for the bgp tests to succeed.
Without it, tests fail as follows:
Failed to import test module: neutron_dynamic_routing.tests.tempest.api.test_bgp_speaker_extensions
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/unittest2/loader.py", line 456, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python2.7/dist-packages/unittest2/loader.py", line 395, in _get_module_from_name
    __import__(name)
  File "/opt/stack/new/neutron-dynamic-routing/neutron_dynamic_routing/tests/tempest/api/test_bgp_speaker_extensions.py", line 21, in <module>
    from neutron_tempest_plugin.api import base
ImportError: No module named neutron_tempest_plugin.api

Resolves-Bug: #1762176
Change-Id: I1d15fe4b1aa43cbb40c85ba448702e3f72052573