Fix POST and PUT methods of REST API
The json attribute was taken from the wrong object, so we got an error
for every POST or PUT request.
   AttributeError: module 'bottle' has no attribute 'json'

Change-Id: Id32e6b0f227ef0f3bde91feac7269635c051e123