Updating required neutron version
build-openstack-sphinx-docs gate was raising an error and -1 on the
gate, due to neutron out of date version (12.0.0). This patch will bring
neutron from 13.0.0.0b1 to the newest version.

Error logs:
   ubuntu-xenial |     'router': constants.L3,
   ubuntu-xenial | AttributeError: 'module' object has no attribute 'L3'

Please see more error logs in the following link
http://logs.openstack.org/04/557904/8/check/build-openstack-sphinx-docs/7a6b1da/job-output.txt.gz#_2018-07-03_04_00_47_083795

Change-Id: I4f31c4bd5368151ff9b236913c1937abdaa793ef